### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by FlameinfirenBr** [kousw/stable-diffusion-webui-daam#37]
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

That's on Forge branch

**Comment by PaleKemono** [comment]
same

**Comment by PaleKemono** [comment]
I think i found the solution. If you are using loras put them at the very end of your prompt, and keep the tags you put in the extension BEFORE any loras (not just the one you are interested in). For example.  "male, day, outside, <lora:pastel-art:1>" . It stopped giving me that error after doing this
